### ISSUE TITLE
Window clips and prevents resize

### ISSUE THREAD

**Issue by daveriedstra** [zsa/wally#10]
The Wally window clips some content and won't allow me to resize it:

![Screenshot from 2019-06-07 11-29-37](https://user-images.githubusercontent.com/3504098/59116211-0e61f800-8919-11e9-93ec-60b65b00346c.png)

Pop!_OS 19.04 using wayland gnome session

Wally looks great, btw!

**Comment by fdidron** [comment]
@daveriedstra I have to say I didn't try running wally on Pop!_OS, I'l spin up a VM and look for a fix.

**Comment by fdidron** [comment]
@daveriedstra A new release of Wally is out and should fix clipping issues: https://github.com/zsa/wally/releases/download/1.1.0-linux/wally

**Comment by daveriedstra** [comment]
@fdidron thanks, still clipping a bit but at least the buttons are visible :)

![Screenshot from 2019-07-05 15-27-54](https://user-images.githubusercontent.com/3504098/60742021-9bf52f80-9f39-11e9-9c2a-fcd24c86000b.png)

**Comment by fdidron** [comment]
@daveriedstra , Oh no ! I increased some of the space, can you try this version:
https://github.com/zsa/wally/releases/download/1.1.0-linux/wally

**Comment by daveriedstra** [comment]
Beautiful, thank you!

![Screenshot from 2019-07-11 11-56-41](https://user-images.githubusercontent.com/3504098/61066140-fb888a80-a3d2-11e9-9c62-cb6665a18d56.png)
