### ISSUE TITLE
Create proper Ubuntu package

### ISSUE THREAD

**Issue by sphinxc0re** [zsa/wally#11]
I would love to see a `.deb` file to make the installation easier. The only problem is that this makes updating the package very uncomfortable so adding a PPA would be perfect. The only problem I see with this is that there is already a package named `wally` on Ubuntu: https://launchpad.net/ubuntu/+source/wally

But you could easily get around this by calling the binary `zsa-wally`.

**Comment by drashna** [comment]
Okay, this shouldn't be too difficult: 
https://help.launchpad.net/Packaging/PPA
https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages
