### ISSUE TITLE
[Mac] High DPI support

### ISSUE THREAD

**Issue by noahtallen** [zsa/wally#13]
Hey there! I just tried Wally on my computer. I'm using a 4k monitor, and the UI looks extremely pixelated. It even shows up when you look closely at this screenshot:

<img width="1487" alt="Screen Shot 2019-06-24 at 5 01 13 PM" src="https://user-images.githubusercontent.com/6265975/60059566-da6d2d80-96a1-11e9-89e2-886c18cde004.png">

It'd be really nice if it behaved nicely with high-dpi resolutions. Do you know where this might be in the code?

**Comment by fdidron** [comment]
Hi there, can you try this version: https://github.com/zsa/wally/releases/tag/1.1.0-osx

My MacBookAir is unfortunately too old to connect to my 4k screen, so I cannot test it myself.

**Comment by noahtallen** [comment]
I’m getting this message when I try to open Wally from the disk image:

> “Wally” is damaged and can’t be opened. You should eject the disk image.

**Comment by fdidron** [comment]
@noahtallen I messed up the release, just reuploaded a version, can you give it a try ?

**Comment by noahtallen** [comment]
Just tried it out, and it looks beautiful on my 4k monitor! Thanks for the fix :)
