### ISSUE TITLE
Archlinux AUR package created

### ISSUE THREAD

**Issue by synaptiko** [zsa/wally#16]
I decided to create an AUR package here: https://aur.archlinux.org/packages/zsa-wally/

Not sure if you want to mention it somewhere in README or on wiki, so I'm just letting you know it's there and it's up you where/if you will place it and close this issue :-)

Keep up the good work, I really like the simplicity of wally-cli!

**Comment by fdidron** [comment]
Thanks so much, I'm an arch user myself :)  I mentioned it on the wiki page: https://github.com/zsa/wally/wiki/Linux-install 

Glad you like the cli, I use it all the time.

There's quite an update coming up soon, i will let you know once live.
