### ISSUE TITLE
Drag'n'Drop support would be nice / is behaving oddly

### ISSUE THREAD

**Issue by Cybolic** [zsa/wally#2]
Currently, when dropping a file on to the wally window, the file contents is loaded into the window and the program has to be closed to be usable again - at least on Linux.
Accepting the file (or disabling dnd support) would be the expected behaviour.

**Comment by fdidron** [comment]
Good catch, an update is coming

**Comment by fdidron** [comment]
@Cybolic version 1.1.0 is out here: https://github.com/zsa/wally/releases/tag/1.1.0-linux with the ability to DND
