### ISSUE TITLE
Can't install on macOS Catalina

### ISSUE THREAD

**Issue by Rhjulskov** [zsa/wally#27]
<img width="426" alt="Screen Shot 2019-09-12 at 5 32 46 PM" src="https://user-images.githubusercontent.com/6944016/64798685-bb38ba80-d583-11e9-9260-6a9455408b19.png">

I'm getting the following error, when trying to install the software.

**Comment by fdidron** [comment]
Hi @Rhjulskov Can you confirm which version of Catalina you are running ?

**Comment by fdidron** [comment]
Hi @Rhjulskov I compiled Wally against the latest beta of Catalina, can you try to download version 1.1.3 here : https://github.com/zsa/wally/releases/download/1.1.3-osx/wally-osx-1.1.3.dmg

Note that the first time you open Wally you might need to right click on its icon and choose Open from the dropdown menu.

**Comment by Rhjulskov** [comment]
@fdidron Thanks.
Both 1.1.2 and 1.1.3. presents the dialog in the original post, when right clicking on choosing Open the first time. Doing it a second time though gives an option to open and I now have it running.

I've tested it with both versions, and I can't see any difference in the behaviour. 
Thank you very much for taking the time :D

**Comment by rafaelfranca** [comment]
I just downloaded 1.1.3 and I still can't open it. I see that same dialog.

**Comment by colincadams** [comment]
I still seem the same issue as well, can this be re opened?

**Comment by rahiminasab** [comment]
I'm also getting the same error and I am using Catalina 10.15.4

**Comment by mike-deboer** [comment]
Seeing the same issue in 10.15.5.

**Comment by suryabhupa** [comment]
Also same problem with 10.15.3.

**Comment by rayyayyar** [comment]
Seeing on 10.15.5

**Comment by suryabhupa** [comment]
Actually, I found a silly workaround!

If I still have the launcher, I double-click it to show the small window with the Wally app, the Applications folder, and the binary wally.cli. Instead of dragging it to the Applications folder, and then opening it through Finder or in the Applications folder, I can just right click the Wally app or right-click and press Open, and it works!

**Comment by fdidron** [comment]
Hello, reopening this issue.
I was able to have the binary signed by Apple . Can you download it again from here: https://github.com/zsa/wally/releases/download/1.1.3-osx/wally-osx-1.1.3.dmg and give it a try ?

**Comment by fdidron** [comment]
A new version of Wally for OSX is available here, it is now signed by Apple, so this kind of issue shouldn't happen anymore https://github.com/zsa/wally/releases/tag/2.0.0-osx
