### ISSUE TITLE
Linux download link still points to version 1.1.0

### ISSUE THREAD

**Issue by kschwank** [zsa/wally#28]
The download link on this page:

https://github.com/zsa/wally/wiki/Linux-install

points to 

https://configure.ergodox-ez.com/wally/linux

which currently starts the download for version 1.1.0. 

I ran into the usb issue https://github.com/zsa/wally/issues/12 that is already fixed in newer versions.

**Comment by fdidron** [comment]
@kschwank Thanks a lot for reporting, I updated the urls
