### ISSUE TITLE
Linux install: superfluous dependency

### ISSUE THREAD

**Issue by ngirard** [zsa/wally#30]
The [Wiki page](https://github.com/zsa/wally/wiki/Linux-install) dedicated to Linux installation advises to install `webkit2gtk`; but as far as I can tell, `libwebkit2gtk` suffices. It has far fewer dependencies, and (I think) comes preinstalled in Ubuntu systems.

So for Debian-based systems, instead of
```sh
sudo apt-get install gtk+3.0 webkit2gtk-4.0 libusb-dev
```

I'd suggest writing
```sh
sudo apt install gtk+3.0 libwebkit2gtk-4.0 libusb-dev
```

**Comment by fdidron** [comment]
Thanks @ngirard , wiki is updated
