### ISSUE TITLE
Implement `--version` option

### ISSUE THREAD

**Issue by ngirard** [zsa/wally#31]
Just downloaded & ran latest Wally V1.1.1 on Ubuntu 19.04.

Got the following messages:
```
17:54:09 info   Found 1 compatible device(s)
17:54:09 info   Probing compatible usb devices
17:54:06 info   Application UI / State initialized
17:54:06 error  Error while opening firmware: open --version: no such file or directory
```

**Comment by DiscoRiver** [comment]
The name of the file the application is trying to open is "--version", so I imagine there was an issue with the command. 

Suggest closing.

**Comment by ngirard** [comment]
I'd rather suggest *implementing* such `--version` option.

Perhaps my title was misleading.

**Comment by DiscoRiver** [comment]
Ah, gotcha. I'll get an update in.

Thanks!
