### ISSUE TITLE
Couldn't claim usb interface, is your board flashed with the latest firmware version?

### ISSUE THREAD

**Issue by javinievas** [zsa/wally#38]
Trying the new TRAIN method.

Getting this error message after selecting the keyboard in the chrome popup:

![image](https://user-images.githubusercontent.com/487162/70522256-122d3c00-1b41-11ea-8e70-64d97882c829.png)

I've flashed the keyboard with the latest firmware version (v15) 

I've followed the step-by-step tutorial and the linux instructions related to the udev rules.

Got:

- Ubuntu 16.04 
- Chrome 78
- Ergodox EZ Glow

I'm posting this issue here, since is where the associated wiki lives, but maybe it is not the right place (?)

**Comment by fdidron** [comment]
Hi @javinievas Did you assign the [Oryx key](https://configure.ergodox-ez.com/planck-ez/layouts/dPvrN/YEdXw/3/11/keys) to your layout ?

**Comment by javinievas** [comment]
That did the trick!

Sorry!

**Comment by fdidron** [comment]
Great to hear @javinievas and no need to be sorry, the error message should include that info, I am updating it.

**Comment by JessicaSachs** [comment]
Hmm, would be helpful to know what the oryx key was from the error message. I'm googling around.
