### ISSUE TITLE
Numpad Issues

### ISSUE THREAD

**Issue by Rostiger** [zsa/wally#46]
This is more a word of advice than an issue. I'm sorry if this isn't the proper place to put it.

In my [layout](https://configure.ergodox-ez.com/planck-ez/layouts/Qa0am/latest) I created a layer (called Extend) with a numpad and mousemode.

In the dropdown for selecting keys there are the options _Numpad_ and _Digits_. When choosing _Numpad_ the keys won't actually work as expected. My suspicion is that this is caused by the number block not actually being enabled (this would need to be set to another key like many keyboard with actual, physical numpads have).

So instead of flashing your keyboard like an idiot five times (like me), just set your numpad keys to digits and you'll be good to go.

**Comment by DiscoRiver** [comment]
The NUMPAD keys function exactly how they are supposed to, meaning that NUMLOCK must be enabled. You can use NUMPAD keys but I would suggest adding the NUMLOCK key to your layer.

Some uses may require the specific use of NUMPAD keys so changing them to digits is not always a viable solution.

**Comment by Rostiger** [comment]
Right, I should have said, it didn't work as **I** expected. Of course it works just like it's supposed to, thanks for the clarification and confirmation!

**Comment by DiscoRiver** [comment]
It's all good! It can't hurt to have this logged for anyone running into similar issues.

**Comment by fdidron** [comment]
@Rostiger glad you got this sorted ! If you run into any other issue, shoot us an email contact@ergodoz-ez.com
