### ISSUE TITLE
Planck EZ issue after flash

### ISSUE THREAD

**Issue by flapsthiscax** [zsa/wally#48]
So I made a layout on oryx, proceeded to flash it with Wally. Then the keyboard no longer registered any layout. It still makes the usb plug in sound and will wake up my computer when I press a key, however when I go to type anything with it nothing happens.

Thanks for the help.

**Comment by charlesrocket** [comment]
Same here

**Comment by fdidron** [comment]
Hi @flapsthiscax , @charlesrocket can you reach our support at contact@ergodox-ez.com so we can dig into your issues ?

**Comment by charlesrocket** [comment]
@fdidron support ignored any mentions of Wally issues.
