### ISSUE TITLE
Reset eeprom for Ergodox EZ

### ISSUE THREAD

**Issue by drashna** [zsa/wally#7]
Well, there is no simple way to do this. 

The best way may be to flash a hex to reset it, and then the destination hex.

For instance: https://github.com/qmk/qmk_toolbox/blob/3d7c9b4c32f1bb7db49e4b0c2a65859fca20bd27/common/atmega32u4_eeprom_reset.hex

And then flash the eventual one, before resetting, if that's possible.

**Comment by fdidron** [comment]
Closing this one for now since Native rewrites of Wally such as https://github.com/zsa/wally-win implements the erase.
