### ISSUE TITLE
Ubuntu instructions don't work on 20.04

### ISSUE THREAD

**Issue by pjroth** [zsa/wally#82]
The https://github.com/zsa/wally/wiki/Linux-install wiki page for Ubuntu says to run:
`sudo apt install gtk+3.0 libwebkit2gtk-4.0 libusb-dev`

I get the following when running:
```
# sudo apt install gtk+3.0 libwebkit2gtk-4.0 libusb-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gtk+3.0
E: Unable to locate package libwebkit2gtk-4.0
```

**Comment by ezebunandu** [comment]
Ran into this as well. If installing only libusb-dev works, then fix would be to edit the reference in the instructions to these two packages.

**Comment by Zie0** [comment]
seems the dependencies for Wally aren't found in ubuntu repository. replicated on Pop!_OS 20.10 (derivative of Ubuntu). please fix

# To Reproduce
0. Update indices and Upgrade Packages
`$ sudo apt update && sudo apt upgrade -y`
1. Install packages outlined in [these instructions](https://github.com/zsa/wally/wiki/Linux-install#12-debian-and-its-derivatives-ubuntu-kali-)
`$ sudo apt install gtk+3.0 libwebkit2gtk-4.0 libusb-dev`

# Results
It seems these packages are not in the official ubuntu repository `http://us.archive.ubuntu.com/ubuntu/`

```
$ sudo apt install gtk+3.0 libwebkit2gtk-4.0 libusb-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gtk+3.0
E: Couldn't find any package by glob 'gtk+3.0'
E: Unable to locate package libwebkit2gtk-4.0
E: Couldn't find any package by glob 'libwebkit2gtk-4.0'
```

# Expected Results
Dependencies are installed

# Env Details
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
$ uname -a
Linux <snip> 5.8.0-7625-generic #26~1604441477~20.10~d41e407-Ubuntu SMP Wed Nov 4 01:25:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by crockels** [comment]
I get the same, unable to flash keyboard.  Is there a workaround?

**Comment by pjroth** [comment]
Looks like the wiki instructions for Ubuntu have been updated per the workaround I used in a previous comment.  

This issue can be closed.
