### ISSUE TITLE
Universal udev rules for linux, does not require custom group

### ISSUE THREAD

**Issue by stinethebean3** [zsa/wally#91]
The current udev rules rely on a custom group, "plugdev", which is an obsolete strategy because udev has built in support for uaccess tagging for several years now. 

The rules I recommend and have tested to work are as follows:

```
 # Rule for the Moonlander
SUBSYSTEM=="usb", ATTR{idVendor}=="3297", ATTR{idProduct}=="1969", TAG+="uaccess", TAG+="udev-acl"
# Rule for the Ergodox EZ, Planck EZ
SUBSYSTEM=="usb", ATTR{idVendor}=="feed", ATTR{idProduct}=="1307|6060", TAG+="uaccess", TAG+="udev-acl"
```

You also don't need the user to log out, but just need the user to restart udev, which is as follows:

```
sudo udevadm control --reload-rules && sudo udevadm trigger
```

Finally, unplug and plug back in the keyboard to make the ensure the new rules take effect.

In addition to working for Ubuntu this should should work on any modern linux distribution. For example, I use Arch.

**Comment by curtisbelt** [comment]
Thanks - this works perfectly on Fedora. I actually didn't get the original rules to work for some reason, but this did. :+1:

**Comment by Mailaender** [comment]
I can confirm that this works on @openSUSE and it is already used by @darix at https://build.opensuse.org/package/view_file/home:darix:apps/ergodox-wally/no-plug-dev.patch

**Comment by putinscousin** [comment]
This does not work on my machine (Fedora Silverblue 33) with the Moonlander.
I have to add the `STMicroelectronics STM Device in DFU Mode` ID to the udev rules.

I'd suggest adding the following line.
`SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="df11", TAG+="uaccess", TAG+="udev-acl"`
